name: CD
on:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: ./app
jobs:
  # ---------- Stage 1 ----------
  retrieve-version:
    name: Retrieve application's version
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.retrieve-version-step.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Retrieve application's version
        id: retrieve-version-step
        run: |
          VERSION=`sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json`
          echo ::set-output name=version::$VERSION
  # ---------- Stage 2 ----------
  tag:
    name: Create tag for release candidate
    runs-on: ubuntu-latest
    needs: retrieve-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Git user email
        run: git config user.email ${{ secrets.GIT_USER_EMAIL }}
      - name: Set Git user name
        run: git config user.name ${{ secrets.GIT_USER_NAME }}
      - name: Create tag
        env:
          APP_VERSION: ${{ needs.retrieve-version.outputs.app-version }}
        run: git tag -a v$APP_VERSION-rc -m "Release candidate v$APP_VERSION"
      - name: Push tag to repository
        run: git push --tags origin
