name: CI
on:
  pull_request:
    branches:
      - develop
      - master
  push: # TODO: Remove after testing
    branches:
      - feature/90
defaults:
  run:
    working-directory: ./app
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install required dependencies
        run: npm install
      - name: Build application
        run: npm run build
