name: CI
on:
  pull_request:
    branches: [develop, master]
    paths:
      - .github/workflows/ci.yml
      - angular.json
      - package*.json
      - src/**
      - tsconfig*.json
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install required dependencies
        run: npm install
      - name: Build application
        run: npm run build
