name: Continuous Integration
on:
  push:
    branches: [master]
    paths:
      - '**/*.json'
      - .github/workflows/ci.yml
      - src/**
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install required dependencies
        run: npm install
      - name: Build application
        run: npm run build
